POST https://hope-health-van.vercel.app/booking/addPatient
Content-Type: application/json

{
	"referenceId": "23849234",
	"name": "John Doe",
	"phone": "+1 (123) 456 - 789",
	"email": "iamauser@mail.com",
	"dob": "September 03, 2004",
	"emergencyContact": [["Father","123 456 7890", "Adam Doe"], ["Mother","123 456 7890", "Jane Doe"]],
	"medicalRecord": "sha512-Oei9OH4tRh0YqU3GxhX79dM mwVgvbZJaSNaRk bshkj0S5cfHcgYakreBjrHwatXKbz IoIdYLxrKim2MjW0Q",
	"history": "sha512-Oei9OH4tRh0YqU3GxhX79dM mwVgvbZJaSNaRk bshkj0S5cfHcgYakreBjrHwatXKbz IoIdYLxrKim2MjW0Q"
}