POST https://hope-health-gzk45yy53-okb-hope-foundation.vercel.app/booking/mobileVan/appointment
Content-Type: application/json

{
	"locations": ["Region A", "Region B", "Region C"],
	"dateTime": "0139 122322",
	"name": "john doe",
	"phone": "+1 (123) 456 - 789",
	"previousUse": true,
	"medicalRecord": ""
}